//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TribalWars.Controls.GridExs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VillageGridExRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VillageGridExRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TribalWars.Controls.GridExs.VillageGridExRes", typeof(VillageGridExRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The church level.
        /// </summary>
        internal static string ChurchTooltip {
            get {
                return ResourceManager.GetString("ChurchTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff..
        /// </summary>
        internal static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kingdom.
        /// </summary>
        internal static string Kingdom {
            get {
                return ResourceManager.GetString("Kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The kingdom the village is located in.
        /// </summary>
        internal static string KingdomTooltip {
            get {
                return ResourceManager.GetString("KingdomTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinates of the village.
        /// </summary>
        internal static string LocationTooltip {
            get {
                return ResourceManager.GetString("LocationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the village.
        /// </summary>
        internal static string NameTooltip {
            get {
                return ResourceManager.GetString("NameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the player.
        /// </summary>
        internal static string Player_NameTooltip {
            get {
                return ResourceManager.GetString("Player_NameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference in player points since previous data.
        /// </summary>
        internal static string Player_PointsDiffTooltip {
            get {
                return ResourceManager.GetString("Player_PointsDiffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points of the player.
        /// </summary>
        internal static string Player_PointsTooltip {
            get {
                return ResourceManager.GetString("Player_PointsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tribe the player switched from since previous data.
        /// </summary>
        internal static string Player_TribeOldTooltip {
            get {
                return ResourceManager.GetString("Player_TribeOldTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tribe the player belongs to.
        /// </summary>
        internal static string Player_TribeTooltip {
            get {
                return ResourceManager.GetString("Player_TribeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villages gained and/or lost since previous data.
        /// </summary>
        internal static string Player_VillagesDiffTooltip {
            get {
                return ResourceManager.GetString("Player_VillagesDiffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villages of the player.
        /// </summary>
        internal static string Player_VillagesTooltip {
            get {
                return ResourceManager.GetString("Player_VillagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show image if at least one village of the player is currently visible on the main map..
        /// </summary>
        internal static string Player_VisibleTooltip {
            get {
                return ResourceManager.GetString("Player_VisibleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The player the village has been nobled from..
        /// </summary>
        internal static string PlayerDifferenceTooltip {
            get {
                return ResourceManager.GetString("PlayerDifferenceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The owner of the village.
        /// </summary>
        internal static string PlayerNameTooltip {
            get {
                return ResourceManager.GetString("PlayerNameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old owner.
        /// </summary>
        internal static string PlayerOld {
            get {
                return ResourceManager.GetString("PlayerOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference in player points since previous data.
        /// </summary>
        internal static string PlayerPointsDiffTooltip {
            get {
                return ResourceManager.GetString("PlayerPointsDiffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The points of the player owning the village.
        /// </summary>
        internal static string PlayerPointsTooltip {
            get {
                return ResourceManager.GetString("PlayerPointsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference in village points since previous data.
        /// </summary>
        internal static string PointsDifferenceTooltip {
            get {
                return ResourceManager.GetString("PointsDifferenceTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points of the village.
        /// </summary>
        internal static string PointsTooltip {
            get {
                return ResourceManager.GetString("PointsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe.
        /// </summary>
        internal static string Tribe {
            get {
                return ResourceManager.GetString("Tribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe name.
        /// </summary>
        internal static string Tribe_NameTooltip {
            get {
                return ResourceManager.GetString("Tribe_NameTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference in players since previous data.
        /// </summary>
        internal static string Tribe_PlayersDiffTooltip {
            get {
                return ResourceManager.GetString("Tribe_PlayersDiffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of players in the tribe.
        /// </summary>
        internal static string Tribe_PlayersTooltip {
            get {
                return ResourceManager.GetString("Tribe_PlayersTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference in total tribe points since previous data.
        /// </summary>
        internal static string Tribe_PointsDiffTooltip {
            get {
                return ResourceManager.GetString("Tribe_PointsDiffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points of the tribe.
        /// </summary>
        internal static string Tribe_PointsTooltip {
            get {
                return ResourceManager.GetString("Tribe_PointsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World rank of the tribe.
        /// </summary>
        internal static string Tribe_RankTooltip {
            get {
                return ResourceManager.GetString("Tribe_RankTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe tag.
        /// </summary>
        internal static string Tribe_TagTooltip {
            get {
                return ResourceManager.GetString("Tribe_TagTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The difference in villages since previous data.
        /// </summary>
        internal static string Tribe_VillagesDiffTooltip {
            get {
                return ResourceManager.GetString("Tribe_VillagesDiffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The total amount of villages in the tribe.
        /// </summary>
        internal static string Tribe_VillagesTooltip {
            get {
                return ResourceManager.GetString("Tribe_VillagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show image if at least one village of the tribe is currently visible on the main map..
        /// </summary>
        internal static string Tribe_VisibleTooltip {
            get {
                return ResourceManager.GetString("Tribe_VisibleTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old tribe.
        /// </summary>
        internal static string TribeOld {
            get {
                return ResourceManager.GetString("TribeOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The rank of the tribe of the player.
        /// </summary>
        internal static string TribeRankTooltip {
            get {
                return ResourceManager.GetString("TribeRankTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag.
        /// </summary>
        internal static string TribeTag {
            get {
                return ResourceManager.GetString("TribeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tribe of the player.
        /// </summary>
        internal static string TribeTagTooltip {
            get {
                return ResourceManager.GetString("TribeTagTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show image for village type (Offense, Defense, Scout, Noble or Farm - Set in &apos;Quick Details&apos; or by using the right click contextmenu).
        /// </summary>
        internal static string TypeTooltip {
            get {
                return ResourceManager.GetString("TypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villages.
        /// </summary>
        internal static string Villages {
            get {
                return ResourceManager.GetString("Villages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The villages the player gained and/or lost since previous data.
        /// </summary>
        internal static string VillagesDiffTooltip {
            get {
                return ResourceManager.GetString("VillagesDiffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount of villages the player has.
        /// </summary>
        internal static string VillagesTooltip {
            get {
                return ResourceManager.GetString("VillagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catapults.
        /// </summary>
        internal static string VillageType_Catapults {
            get {
                return ResourceManager.GetString("VillageType_Catapults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string VillageType_Comments {
            get {
                return ResourceManager.GetString("VillageType_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defensive.
        /// </summary>
        internal static string VillageType_Defensive {
            get {
                return ResourceManager.GetString("VillageType_Defensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        internal static string VillageType_Farm {
            get {
                return ResourceManager.GetString("VillageType_Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobles.
        /// </summary>
        internal static string VillageType_Noble {
            get {
                return ResourceManager.GetString("VillageType_Noble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensive.
        /// </summary>
        internal static string VillageType_Offensive {
            get {
                return ResourceManager.GetString("VillageType_Offensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scouts.
        /// </summary>
        internal static string VillageType_Scouts {
            get {
                return ResourceManager.GetString("VillageType_Scouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently visible on the map.
        /// </summary>
        internal static string VisibleCellTooltip {
            get {
                return ResourceManager.GetString("VisibleCellTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show image if village is currently visible on the main map.
        /// </summary>
        internal static string VisibleTooltip {
            get {
                return ResourceManager.GetString("VisibleTooltip", resourceCulture);
            }
        }
    }
}
