//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TribalWars.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TWWords {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TWWords() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TribalWars.Translations.TWWords", typeof(TWWords).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academy.
        /// </summary>
        internal static string Academy {
            get {
                return ResourceManager.GetString("Academy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barracks.
        /// </summary>
        internal static string Barracks {
            get {
                return ResourceManager.GetString("Barracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string BuildingLevel {
            get {
                return ResourceManager.GetString("BuildingLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildings.
        /// </summary>
        internal static string Buildings {
            get {
                return ResourceManager.GetString("Buildings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay.
        /// </summary>
        internal static string Clay {
            get {
                return ResourceManager.GetString("Clay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K.
        /// </summary>
        internal static string ContinentAbreviation {
            get {
                return ResourceManager.GetString("ContinentAbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demolition.
        /// </summary>
        internal static string Demolition {
            get {
                return ResourceManager.GetString("Demolition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        internal static string Farm {
            get {
                return ResourceManager.GetString("Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiding Place.
        /// </summary>
        internal static string HidingPlace {
            get {
                return ResourceManager.GetString("HidingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iron.
        /// </summary>
        internal static string Iron {
            get {
                return ResourceManager.GetString("Iron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        internal static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morale.
        /// </summary>
        internal static string Morale {
            get {
                return ResourceManager.GetString("Morale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rally Point.
        /// </summary>
        internal static string RallyPoint {
            get {
                return ResourceManager.GetString("RallyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker.
        /// </summary>
        internal static string ReportAttacker {
            get {
                return ResourceManager.GetString("ReportAttacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attacker.
        /// </summary>
        internal static string ReportAttackerLCase {
            get {
                return ResourceManager.GetString("ReportAttackerLCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage by catapult bombardment.
        /// </summary>
        internal static string ReportCatas {
            get {
                return ResourceManager.GetString("ReportCatas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to level.
        /// </summary>
        internal static string ReportCatasBetween {
            get {
                return ResourceManager.GetString("ReportCatasBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been damaged and downgraded from level.
        /// </summary>
        internal static string ReportCatasPre {
            get {
                return ResourceManager.GetString("ReportCatasPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        internal static string ReportDefender {
            get {
                return ResourceManager.GetString("ReportDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defender.
        /// </summary>
        internal static string ReportDefenderLCase {
            get {
                return ResourceManager.GetString("ReportDefenderLCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espionage.
        /// </summary>
        internal static string ReportEspionage {
            get {
                return ResourceManager.GetString("ReportEspionage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has won.
        /// </summary>
        internal static string ReportHasWon {
            get {
                return ResourceManager.GetString("ReportHasWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haul.
        /// </summary>
        internal static string ReportHaul {
            get {
                return ResourceManager.GetString("ReportHaul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses.
        /// </summary>
        internal static string ReportLosses {
            get {
                return ResourceManager.GetString("ReportLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change of Loyalty.
        /// </summary>
        internal static string ReportLoyalty {
            get {
                return ResourceManager.GetString("ReportLoyalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string ReportLoyaltyBetween {
            get {
                return ResourceManager.GetString("ReportLoyaltyBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loyalty loss from.
        /// </summary>
        internal static string ReportLoyaltyPre {
            get {
                return ResourceManager.GetString("ReportLoyaltyPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of your troops have returned. No information about the strength of your enemy&apos;s army could be collected..
        /// </summary>
        internal static string ReportNoDefense {
            get {
                return ResourceManager.GetString("ReportNoDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string ReportQuantity {
            get {
                return ResourceManager.GetString("ReportQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage by rams.
        /// </summary>
        internal static string ReportRams {
            get {
                return ResourceManager.GetString("ReportRams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to level.
        /// </summary>
        internal static string ReportRamsBetween {
            get {
                return ResourceManager.GetString("ReportRamsBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wall has been damaged and downgraded from level.
        /// </summary>
        internal static string ReportRamsPre {
            get {
                return ResourceManager.GetString("ReportRamsPre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources scouted.
        /// </summary>
        internal static string ReportResourcesScouted {
            get {
                return ResourceManager.GetString("ReportResourcesScouted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string ReportResourcesScoutedNone {
            get {
                return ResourceManager.GetString("ReportResourcesScoutedNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string ReportSent {
            get {
                return ResourceManager.GetString("ReportSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string ReportSubject {
            get {
                return ResourceManager.GetString("ReportSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender&apos;s troops, that were in transit.
        /// </summary>
        internal static string ReportUnitsInTransit {
            get {
                return ResourceManager.GetString("ReportUnitsInTransit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender&apos;s troops in other villages.
        /// </summary>
        internal static string ReportUnitsOtherVillages {
            get {
                return ResourceManager.GetString("ReportUnitsOtherVillages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units outside of village.
        /// </summary>
        internal static string ReportUnitsOutside {
            get {
                return ResourceManager.GetString("ReportUnitsOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable.
        /// </summary>
        internal static string Stable {
            get {
                return ResourceManager.GetString("Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statue.
        /// </summary>
        internal static string Statue {
            get {
                return ResourceManager.GetString("Statue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        internal static string The {
            get {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village.
        /// </summary>
        internal static string Village {
            get {
                return ResourceManager.GetString("Village", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Village Headquarters.
        /// </summary>
        internal static string VillageHeadquarters {
            get {
                return ResourceManager.GetString("VillageHeadquarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall.
        /// </summary>
        internal static string Wall {
            get {
                return ResourceManager.GetString("Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        internal static string Wood {
            get {
                return ResourceManager.GetString("Wood", resourceCulture);
            }
        }
    }
}
