//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TribalWars.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TribalWars.Controls.ControlsRes", typeof(ControlsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press +, - and the arrow keys to 
        ///grow and shrink the area.
        ///
        ///Left click to save the area.
        ///Right click to cancel.
        ///
        ///Press &apos;s&apos; to remove this tooltip..
        /// </summary>
        internal static string ActiveRectangleManipulator_Help {
            get {
                return ResourceManager.GetString("ActiveRectangleManipulator_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring Area.
        /// </summary>
        internal static string ActiveRectangleManipulator_HelpTitle {
            get {
                return ResourceManager.GetString("ActiveRectangleManipulator_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Monitoring Area.
        /// </summary>
        internal static string ActiveRectangleManipulator_Set {
            get {
                return ResourceManager.GetString("ActiveRectangleManipulator_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this as the new Monitoring Area? This is the area you monitor growth for in the Monitoring tab..
        /// </summary>
        internal static string ActiveRectangleManipulator_SetTitle {
            get {
                return ResourceManager.GetString("ActiveRectangleManipulator_SetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} villages to attackers pool.
        /// </summary>
        internal static string AttackersPoolContextMenu_AddXToPool {
            get {
                return ResourceManager.GetString("AttackersPoolContextMenu_AddXToPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using the attack plan search function, don&apos;t search through all your villages but only select villages from those added to the &apos;attackers pool&apos;..
        /// </summary>
        internal static string AttackersPoolContextMenu_AddXVillagesTooltip {
            get {
                return ResourceManager.GetString("AttackersPoolContextMenu_AddXVillagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival date: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_ArrivalDate {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on your own villages to add them as attacking (or defending) villages..
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Help_1 {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or easier: use the search function (binoculars icon) in the &apos;Plan Attacks&apos; panel on the left!.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Help_2 {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Help_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not yet set who you are so right click wont work! You can do so using the menu &apos;World&apos; -&gt; &apos;Set Active Player&apos;.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Help_NoYou {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Help_NoYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Points {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send on: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_SendOn {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_SendOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Target {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel time: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_TravelTime {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_TravelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attackers pool depleted!.
        /// </summary>
        internal static string AttackPlanCollectionControl_AttackersPoolDepleted {
            get {
                return ResourceManager.GetString("AttackPlanCollectionControl_AttackersPoolDepleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attackers pool.
        /// </summary>
        internal static string AttackPlanCollectionControl_AttackersPoolTitle {
            get {
                return ResourceManager.GetString("AttackPlanCollectionControl_AttackersPoolTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your attackers pool is empty.
        ///In the top menu, choose &apos;Windows&apos; &gt; &apos;Manage your villages&apos; to learn how to create one!.
        /// </summary>
        internal static string AttackPlanCollectionControl_EmptyAttackersPool {
            get {
                return ResourceManager.GetString("AttackPlanCollectionControl_EmptyAttackersPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} ({2}pts) - {3} attacks.
        /// </summary>
        internal static string AttackPlanCollectionControl_PlanExportCaption {
            get {
                return ResourceManager.GetString("AttackPlanCollectionControl_PlanExportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0}.
        /// </summary>
        internal static string AttackPlanCollectionControl_PlanExportCaption_OnPlayer {
            get {
                return ResourceManager.GetString("AttackPlanCollectionControl_PlanExportCaption_OnPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack {0}.
        /// </summary>
        internal static string AttackPlanExporter_AttackX {
            get {
                return ResourceManager.GetString("AttackPlanExporter_AttackX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTN: Another attack coming up {0} seconds later!.
        /// </summary>
        internal static string AttackPlanExporter_Attn_AnotherAttackInXSeconds {
            get {
                return ResourceManager.GetString("AttackPlanExporter_Attn_AnotherAttackInXSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTN: {0} more attacks coming up soon!.
        /// </summary>
        internal static string AttackPlanExporter_Attn_MoreAttacksComingSoon {
            get {
                return ResourceManager.GetString("AttackPlanExporter_Attn_MoreAttacksComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export time:.
        /// </summary>
        internal static string AttackPlanExporter_ExportTime {
            get {
                return ResourceManager.GetString("AttackPlanExporter_ExportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from {1}.
        /// </summary>
        internal static string AttackPlanExporter_ImgFromCoordinates {
            get {
                return ResourceManager.GetString("AttackPlanExporter_ImgFromCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Attack Plan ***.
        /// </summary>
        internal static string AttackPlanExporter_Title {
            get {
                return ResourceManager.GetString("AttackPlanExporter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total attacks: {0}.
        /// </summary>
        internal static string AttackPlanExporter_TotalAttacks {
            get {
                return ResourceManager.GetString("AttackPlanExporter_TotalAttacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival time when sent NOW.
        /// </summary>
        internal static string AttackPlanFromControl_ArrivalTimeWhenSentNow {
            get {
                return ResourceManager.GetString("AttackPlanFromControl_ArrivalTimeWhenSentNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send troops:.
        /// </summary>
        internal static string AttackPlanFromControl_SendTroops {
            get {
                return ResourceManager.GetString("AttackPlanFromControl_SendTroops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0}pts|{1}vils).
        /// </summary>
        internal static string BbCode_Player {
            get {
                return ResourceManager.GetString("BbCode_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [b]{5}[/b] [ally]{0}[/ally]{3}Points: {2:#,0}pts ({6:#,0}avg){3}Players: {1}{3}Rank: {4}.
        /// </summary>
        internal static string BbCode_Tribe {
            get {
                return ResourceManager.GetString("BbCode_Tribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *DEAD*.
        /// </summary>
        internal static string BbCode_TribeExtended_Dead {
            get {
                return ResourceManager.GetString("BbCode_TribeExtended_Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Details.
        /// </summary>
        internal static string BbCode_TribeExtended_Title {
            get {
                return ResourceManager.GetString("BbCode_TribeExtended_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0:#,0}pts).
        /// </summary>
        internal static string BbCode_VillagePoints {
            get {
                return ResourceManager.GetString("BbCode_VillagePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church.
        /// </summary>
        internal static string Church {
            get {
                return ResourceManager.GetString("Church", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0}.
        /// </summary>
        internal static string Church_Level {
            get {
                return ResourceManager.GetString("Church_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No church.
        /// </summary>
        internal static string Church_None {
            get {
                return ResourceManager.GetString("Church_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinpoint.
        /// </summary>
        internal static string ContextMenu_Pinpoint {
            get {
                return ResourceManager.GetString("ContextMenu_Pinpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinpoint &amp;&amp; Center.
        /// </summary>
        internal static string ContextMenu_PinpointAndCenter {
            get {
                return ResourceManager.GetString("ContextMenu_PinpointAndCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Details.
        /// </summary>
        internal static string ContextMenu_QuickDetails {
            get {
                return ResourceManager.GetString("ContextMenu_QuickDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBCode.
        /// </summary>
        internal static string ContextMenu_ToBbCode {
            get {
                return ResourceManager.GetString("ContextMenu_ToBbCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string ContextMenu_ToBbCodeOperation {
            get {
                return ResourceManager.GetString("ContextMenu_ToBbCodeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To clipboard.
        /// </summary>
        internal static string ContextMenu_ToClipboard {
            get {
                return ResourceManager.GetString("ContextMenu_ToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TW Guest.
        /// </summary>
        internal static string ContextMenu_TwGuest {
            get {
                return ResourceManager.GetString("ContextMenu_TwGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TWStats.
        /// </summary>
        internal static string ContextMenu_TwStats {
            get {
                return ResourceManager.GetString("ContextMenu_TwStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        internal static string Date_DiffDays {
            get {
                return ResourceManager.GetString("Date_DiffDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        internal static string Date_DiffHours {
            get {
                return ResourceManager.GetString("Date_DiffHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has been {0} hours since you downloaded the latest TW data.\nDownload now?.
        /// </summary>
        internal static string InternalStructure_DownloadNewTwSnapshot {
            get {
                return ResourceManager.GetString("InternalStructure_DownloadNewTwSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download latest data.
        /// </summary>
        internal static string InternalStructure_DownloadNewTwSnapshotTitle {
            get {
                return ResourceManager.GetString("InternalStructure_DownloadNewTwSnapshotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only download the data once per hour! (TW data is not updated any quicker).
        /// </summary>
        internal static string InternalStructure_DownloadOnlyOncePerHour {
            get {
                return ResourceManager.GetString("InternalStructure_DownloadOnlyOncePerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to village, player, tribe....
        /// </summary>
        internal static string LocationChangerControl_PlaceHolder {
            get {
                return ResourceManager.GetString("LocationChangerControl_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change map zoom level.
        /// </summary>
        internal static string LocationChangerControl_ZoomControl_Tooltip {
            get {
                return ResourceManager.GetString("LocationChangerControl_ZoomControl_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable marker.
        /// </summary>
        internal static string MarkerContextMenu_Disable {
            get {
                return ResourceManager.GetString("MarkerContextMenu_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate marker.
        /// </summary>
        internal static string MarkerContextMenu_Enable {
            get {
                return ResourceManager.GetString("MarkerContextMenu_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner color.
        /// </summary>
        internal static string MarkerContextMenu_InnerColor {
            get {
                return ResourceManager.GetString("MarkerContextMenu_InnerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main color.
        /// </summary>
        internal static string MarkerContextMenu_MainColor {
            get {
                return ResourceManager.GetString("MarkerContextMenu_MainColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker.
        /// </summary>
        internal static string MarkerContextMenu_Marker {
            get {
                return ResourceManager.GetString("MarkerContextMenu_Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark {0}.
        /// </summary>
        internal static string MarkerContextMenu_MarkX {
            get {
                return ResourceManager.GetString("MarkerContextMenu_MarkX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MarkerContextMenu_View {
            get {
                return ResourceManager.GetString("MarkerContextMenu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Current).
        /// </summary>
        internal static string MonitoringControl_DateCurrent {
            get {
                return ResourceManager.GetString("MonitoringControl_DateCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Previous).
        /// </summary>
        internal static string MonitoringControl_DatePrevious {
            get {
                return ResourceManager.GetString("MonitoringControl_DatePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clusters.
        /// </summary>
        internal static string NoPolygonContextMenu_Clusters {
            get {
                return ResourceManager.GetString("NoPolygonContextMenu_Clusters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all clusters ({0}).
        /// </summary>
        internal static string NoPolygonContextMenu_DeleteAll {
            get {
                return ResourceManager.GetString("NoPolygonContextMenu_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all clusters?.
        /// </summary>
        internal static string NoPolygonContextMenu_DeleteAllConfirm {
            get {
                return ResourceManager.GetString("NoPolygonContextMenu_DeleteAllConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and hold the left mouse button to draw the area (=cluster) you want to generate BB codes for.
        ///Use Control to force drawing vertically and Shift to force drawing horizontally. (in case you don&apos;t have a steady hand:)
        ///Click on a cluster to select it. Use Del to remove the selected cluster. Use the arrow keys to move it.
        ///
        ///Right click inside/outside a cluster for more options..
        /// </summary>
        internal static string NoPolygonContextMenu_Help {
            get {
                return ResourceManager.GetString("NoPolygonContextMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string NoPolygonContextMenu_HelpCaption {
            get {
                return ResourceManager.GetString("NoPolygonContextMenu_HelpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all visible clusters ({0}).
        /// </summary>
        internal static string NoPolygonContextMenu_HideAll {
            get {
                return ResourceManager.GetString("NoPolygonContextMenu_HideAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulate villages from all clusters.
        /// </summary>
        internal static string NoPolygonContextMenu_ManipulateAll {
            get {
                return ResourceManager.GetString("NoPolygonContextMenu_ManipulateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all hidden clusters ({0}).
        /// </summary>
        internal static string NoPolygonContextMenu_ShowAll {
            get {
                return ResourceManager.GetString("NoPolygonContextMenu_ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show attack plans.
        /// </summary>
        internal static string NoVillageAttackContextMenu_AlwaysShowAttackPlans {
            get {
                return ResourceManager.GetString("NoVillageAttackContextMenu_AlwaysShowAttackPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &apos;arrival times when sent now&apos; in attack planner.
        /// </summary>
        internal static string NoVillageAttackContextMenu_ShowArrivalTimesWhenSentNow {
            get {
                return ResourceManager.GetString("NoVillageAttackContextMenu_ShowArrivalTimesWhenSentNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show non-active plan attackers.
        /// </summary>
        internal static string NoVillageAttackContextMenu_ShowNonActivePlanAttackers {
            get {
                return ResourceManager.GetString("NoVillageAttackContextMenu_ShowNonActivePlanAttackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show non-active plan targets.
        /// </summary>
        internal static string NoVillageAttackContextMenu_ShowNonActivePlanTargets {
            get {
                return ResourceManager.GetString("NoVillageAttackContextMenu_ShowNonActivePlanTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        internal static string NoVillageContextMenu_BackgroundColor {
            get {
                return ResourceManager.GetString("NoVillageContextMenu_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center here.
        /// </summary>
        internal static string NoVillageContextMenu_CenterHere {
            get {
                return ResourceManager.GetString("NoVillageContextMenu_CenterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show continent lines.
        /// </summary>
        internal static string NoVillageContextMenu_ContinentLines {
            get {
                return ResourceManager.GetString("NoVillageContextMenu_ContinentLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all abandoned.
        /// </summary>
        internal static string NoVillageContextMenu_HideAbandoned {
            get {
                return ResourceManager.GetString("NoVillageContextMenu_HideAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show province lines.
        /// </summary>
        internal static string NoVillageContextMenu_ProvinceLines {
            get {
                return ResourceManager.GetString("NoVillageContextMenu_ProvinceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Home.
        /// </summary>
        internal static string NoVillageContextMenu_SetHome {
            get {
                return ResourceManager.GetString("NoVillageContextMenu_SetHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show marked only.
        /// </summary>
        internal static string NoVillageContextMenu_ShowMarkedOnly {
            get {
                return ResourceManager.GetString("NoVillageContextMenu_ShowMarkedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show village &amp;tooltip.
        /// </summary>
        internal static string NoVillageContextMenu_ShowVillageTooltip {
            get {
                return ResourceManager.GetString("NoVillageContextMenu_ShowVillageTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is me!.
        /// </summary>
        internal static string PlayerContextMenu_ThisIsMe {
            get {
                return ResourceManager.GetString("PlayerContextMenu_ThisIsMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next part:.
        /// </summary>
        internal static string PlayerOperation_NextPart {
            get {
                return ResourceManager.GetString("PlayerOperation_NextPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string PlayerOperation_Target {
            get {
                return ResourceManager.GetString("PlayerOperation_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{1} ({0} points).
        /// </summary>
        internal static string PlayerOrTribeRow_Text {
            get {
                return ResourceManager.GetString("PlayerOrTribeRow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string PolygonContextMenu_Color {
            get {
                return ResourceManager.GetString("PolygonContextMenu_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string PolygonContextMenu_Delete {
            get {
                return ResourceManager.GetString("PolygonContextMenu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string PolygonContextMenu_Group {
            get {
                return ResourceManager.GetString("PolygonContextMenu_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string PolygonContextMenu_Hide {
            get {
                return ResourceManager.GetString("PolygonContextMenu_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manipulate villages in &quot;{0}&quot;.
        /// </summary>
        internal static string PolygonContextMenu_Manipulate {
            get {
                return ResourceManager.GetString("PolygonContextMenu_Manipulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PolygonContextMenu_Name {
            get {
                return ResourceManager.GetString("PolygonContextMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string PolygonContextMenu_Show {
            get {
                return ResourceManager.GetString("PolygonContextMenu_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing in the grid yet. Try &apos;{0}&apos;?.
        /// </summary>
        internal static string PolygonControl_EmptyGrid {
            get {
                return ResourceManager.GetString("PolygonControl_EmptyGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} / {2} villages).
        /// </summary>
        internal static string PolygonControl_Grid_GroupText {
            get {
                return ResourceManager.GetString("PolygonControl_Grid_GroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current modus: {0}.
        /// </summary>
        internal static string PolygonControl_ModusCaption {
            get {
                return ResourceManager.GetString("PolygonControl_ModusCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not yet defined any clusters.
        ///I have activated cluster drawing for you, you can go back to the main map and create some now!
        ///
        ///Click and hold left mouse button to start drawing!
        ///Or... Right click on the map for more help..
        /// </summary>
        internal static string PolygonControl_StartHelp {
            get {
                return ResourceManager.GetString("PolygonControl_StartHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No clusters!.
        /// </summary>
        internal static string PolygonControl_StartHelpTitle {
            get {
                return ResourceManager.GetString("PolygonControl_StartHelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBCodes for {0} villages have been placed on the clipboard!.
        /// </summary>
        internal static string PolygonControl_ToClipboard {
            get {
                return ResourceManager.GetString("PolygonControl_ToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBCodes on clipboard.
        /// </summary>
        internal static string PolygonControl_ToClipboardTitle {
            get {
                return ResourceManager.GetString("PolygonControl_ToClipboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cluster {0}.
        /// </summary>
        internal static string PolygonDrawerManipulator_NewClusterName {
            get {
                return ResourceManager.GetString("PolygonDrawerManipulator_NewClusterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments:.
        /// </summary>
        internal static string Tooltip_Comments {
            get {
                return ResourceManager.GetString("Tooltip_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0}.
        /// </summary>
        internal static string Tooltip_Name {
            get {
                return ResourceManager.GetString("Tooltip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points: {0}.
        /// </summary>
        internal static string Tooltip_Points {
            get {
                return ResourceManager.GetString("Tooltip_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank: {0}.
        /// </summary>
        internal static string Tooltip_Rank {
            get {
                return ResourceManager.GetString("Tooltip_Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe: {0} (#{1}).
        /// </summary>
        internal static string Tooltip_Tribe {
            get {
                return ResourceManager.GetString("Tooltip_Tribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players: {0} {1}.
        /// </summary>
        internal static string Tooltip_Tribe_Players {
            get {
                return ResourceManager.GetString("Tooltip_Tribe_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongest:.
        /// </summary>
        internal static string Tooltip_Tribe_StrongestPlayers {
            get {
                return ResourceManager.GetString("Tooltip_Tribe_StrongestPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tribe: {0}.
        /// </summary>
        internal static string Tooltip_TribeShort {
            get {
                return ResourceManager.GetString("Tooltip_TribeShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villages: {0}.
        /// </summary>
        internal static string Tooltip_Villages {
            get {
                return ResourceManager.GetString("Tooltip_Villages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} | {2}plys).
        /// </summary>
        internal static string ToString_Tribe {
            get {
                return ResourceManager.GetString("ToString_Tribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {0} at {1}.
        /// </summary>
        internal static string TwDate_Full {
            get {
                return ResourceManager.GetString("TwDate_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1}.
        /// </summary>
        internal static string TwDate_FullShort {
            get {
                return ResourceManager.GetString("TwDate_FullShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today at {0}.
        /// </summary>
        internal static string TwDate_TodayAt {
            get {
                return ResourceManager.GetString("TwDate_TodayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow at {0}.
        /// </summary>
        internal static string TwDate_TomorrowAt {
            get {
                return ResourceManager.GetString("TwDate_TomorrowAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new attacker to plan.
        /// </summary>
        internal static string VillageContextMenu_AddToAttackPlan {
            get {
                return ResourceManager.GetString("VillageContextMenu_AddToAttackPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete attack plan.
        /// </summary>
        internal static string VillageContextMenu_DeleteAttackPlan {
            get {
                return ResourceManager.GetString("VillageContextMenu_DeleteAttackPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete attacker from plan.
        /// </summary>
        internal static string VillageContextMenu_DeleteFromAttackPlan {
            get {
                return ResourceManager.GetString("VillageContextMenu_DeleteFromAttackPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New attack plan.
        /// </summary>
        internal static string VillageContextMenu_NewAttackPlan {
            get {
                return ResourceManager.GetString("VillageContextMenu_NewAttackPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobled from {0}.
        /// </summary>
        internal static string VillageContextMenu_NobledFrom {
            get {
                return ResourceManager.GetString("VillageContextMenu_NobledFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove purpose.
        /// </summary>
        internal static string VillageContextMenu_RemovePurpose {
            get {
                return ResourceManager.GetString("VillageContextMenu_RemovePurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select attack plan.
        /// </summary>
        internal static string VillageContextMenu_SelectAttackPlan {
            get {
                return ResourceManager.GetString("VillageContextMenu_SelectAttackPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set purpose.
        /// </summary>
        internal static string VillageContextMenu_SetPurpose {
            get {
                return ResourceManager.GetString("VillageContextMenu_SetPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to add {0} villages as attack targets. Continue?.
        /// </summary>
        internal static string VillagesContextMenu_AddTargetsWarning {
            get {
                return ResourceManager.GetString("VillagesContextMenu_AddTargetsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack these villages.
        /// </summary>
        internal static string VillagesContextMenu_AttackThem {
            get {
                return ResourceManager.GetString("VillagesContextMenu_AttackThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the purpose for {0} villages to {1}?\nThis action cannot be undone!.
        /// </summary>
        internal static string VillagesContextMenu_ChangePurposeWarning {
            get {
                return ResourceManager.GetString("VillagesContextMenu_ChangePurposeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defend these villages.
        /// </summary>
        internal static string VillagesContextMenu_DefendThem {
            get {
                return ResourceManager.GetString("VillagesContextMenu_DefendThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove all existing purpose of {0} villages?\nThis action cannot be undone!.
        /// </summary>
        internal static string VillagesContextMenu_RemovePurposeWarning {
            get {
                return ResourceManager.GetString("VillagesContextMenu_RemovePurposeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned.
        /// </summary>
        internal static string VillageTooltip_Abandoned {
            get {
                return ResourceManager.GetString("VillageTooltip_Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandoned by {0} ({1}).
        /// </summary>
        internal static string VillageTooltip_AbandonedBy {
            get {
                return ResourceManager.GetString("VillageTooltip_AbandonedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church level {0}.
        /// </summary>
        internal static string VillageTooltip_ChurchLevel {
            get {
                return ResourceManager.GetString("VillageTooltip_ChurchLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobled from {0} (#{1}|{2} points).
        /// </summary>
        internal static string VillageTooltip_NobledFrom {
            get {
                return ResourceManager.GetString("VillageTooltip_NobledFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobled abandoned.
        /// </summary>
        internal static string VillageTooltip_NobledFromAbandoned {
            get {
                return ResourceManager.GetString("VillageTooltip_NobledFromAbandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner: {0} (#{1} | {2} points).
        /// </summary>
        internal static string VillageTooltip_Owner {
            get {
                return ResourceManager.GetString("VillageTooltip_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed from {0}.
        /// </summary>
        internal static string VillageTooltip_TribeChanged {
            get {
                return ResourceManager.GetString("VillageTooltip_TribeChanged", resourceCulture);
            }
        }
    }
}
