//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TribalWars.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TribalWars.Controls.ControlsRes", typeof(ControlsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0} villages to attackers pool.
        /// </summary>
        internal static string AttackersPoolContextMenu_AddXToPool {
            get {
                return ResourceManager.GetString("AttackersPoolContextMenu_AddXToPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using the attack plan search function, don&apos;t search through all your villages but only select villages from those added to the &apos;attackers pool&apos;..
        /// </summary>
        internal static string AttackersPoolContextMenu_AddXVillagesTooltip {
            get {
                return ResourceManager.GetString("AttackersPoolContextMenu_AddXVillagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival date: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_ArrivalDate {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right click on your own villages to add them as attacking (or defending) villages..
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Help_1 {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Help_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or easier: use the search function (binoculars icon) in the &apos;Plan Attacks&apos; panel on the left!.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Help_2 {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Help_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not yet set who you are so right click wont work! You can do so using the menu &apos;World&apos; -&gt; &apos;Set Active Player&apos;.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Help_NoYou {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Help_NoYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Points {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send on: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_SendOn {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_SendOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_Target {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel time: {0}.
        /// </summary>
        internal static string AttackManipulatorManager_Tooltip_TravelTime {
            get {
                return ResourceManager.GetString("AttackManipulatorManager_Tooltip_TravelTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack {0}.
        /// </summary>
        internal static string AttackPlanExporter_AttackX {
            get {
                return ResourceManager.GetString("AttackPlanExporter_AttackX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTN: Another attack coming up {0} seconds later!.
        /// </summary>
        internal static string AttackPlanExporter_Attn_AnotherAttackInXSeconds {
            get {
                return ResourceManager.GetString("AttackPlanExporter_Attn_AnotherAttackInXSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATTN: {0} more attacks coming up soon!.
        /// </summary>
        internal static string AttackPlanExporter_Attn_MoreAttacksComingSoon {
            get {
                return ResourceManager.GetString("AttackPlanExporter_Attn_MoreAttacksComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export time:.
        /// </summary>
        internal static string AttackPlanExporter_ExportTime {
            get {
                return ResourceManager.GetString("AttackPlanExporter_ExportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from {1}.
        /// </summary>
        internal static string AttackPlanExporter_ImgFromCoordinates {
            get {
                return ResourceManager.GetString("AttackPlanExporter_ImgFromCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Attack Plan ***.
        /// </summary>
        internal static string AttackPlanExporter_Title {
            get {
                return ResourceManager.GetString("AttackPlanExporter_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total attacks: {0}.
        /// </summary>
        internal static string AttackPlanExporter_TotalAttacks {
            get {
                return ResourceManager.GetString("AttackPlanExporter_TotalAttacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival time when sent NOW.
        /// </summary>
        internal static string AttackPlanFromControl_ArrivalTimeWhenSentNow {
            get {
                return ResourceManager.GetString("AttackPlanFromControl_ArrivalTimeWhenSentNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send troops:.
        /// </summary>
        internal static string AttackPlanFromControl_SendTroops {
            get {
                return ResourceManager.GetString("AttackPlanFromControl_SendTroops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to village, player, tribe....
        /// </summary>
        internal static string LocationChangerControl_PlaceHolder {
            get {
                return ResourceManager.GetString("LocationChangerControl_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change map zoom level.
        /// </summary>
        internal static string LocationChangerControl_ZoomControl_Tooltip {
            get {
                return ResourceManager.GetString("LocationChangerControl_ZoomControl_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable marker.
        /// </summary>
        internal static string MarkerContextMenu_Disable {
            get {
                return ResourceManager.GetString("MarkerContextMenu_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate marker.
        /// </summary>
        internal static string MarkerContextMenu_Enable {
            get {
                return ResourceManager.GetString("MarkerContextMenu_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner color.
        /// </summary>
        internal static string MarkerContextMenu_InnerColor {
            get {
                return ResourceManager.GetString("MarkerContextMenu_InnerColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main color.
        /// </summary>
        internal static string MarkerContextMenu_MainColor {
            get {
                return ResourceManager.GetString("MarkerContextMenu_MainColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marker.
        /// </summary>
        internal static string MarkerContextMenu_Marker {
            get {
                return ResourceManager.GetString("MarkerContextMenu_Marker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark {0}.
        /// </summary>
        internal static string MarkerContextMenu_MarkX {
            get {
                return ResourceManager.GetString("MarkerContextMenu_MarkX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MarkerContextMenu_View {
            get {
                return ResourceManager.GetString("MarkerContextMenu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always show attack plans.
        /// </summary>
        internal static string NoVillageAttackContextMenu_AlwaysShowAttackPlans {
            get {
                return ResourceManager.GetString("NoVillageAttackContextMenu_AlwaysShowAttackPlans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &apos;arrival times when sent now&apos; in attack planner.
        /// </summary>
        internal static string NoVillageAttackContextMenu_ShowArrivalTimesWhenSentNow {
            get {
                return ResourceManager.GetString("NoVillageAttackContextMenu_ShowArrivalTimesWhenSentNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show non-active plan attackers.
        /// </summary>
        internal static string NoVillageAttackContextMenu_ShowNonActivePlanAttackers {
            get {
                return ResourceManager.GetString("NoVillageAttackContextMenu_ShowNonActivePlanAttackers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show non-active plan targets.
        /// </summary>
        internal static string NoVillageAttackContextMenu_ShowNonActivePlanTargets {
            get {
                return ResourceManager.GetString("NoVillageAttackContextMenu_ShowNonActivePlanTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{1} ({0} points).
        /// </summary>
        internal static string PlayerOrTribeRow_Text {
            get {
                return ResourceManager.GetString("PlayerOrTribeRow_Text", resourceCulture);
            }
        }
    }
}
