//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TribalWars.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FormRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TribalWars.Forms.FormRes", typeof(FormRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No world selected!.
        /// </summary>
        internal static string LoadWorldForm_NoWorldSelected {
            get {
                return ResourceManager.GetString("LoadWorldForm_NoWorldSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on.
        /// </summary>
        internal static string LoadWorldForm_SettingsGrid_ColumnCreatedAt {
            get {
                return ResourceManager.GetString("LoadWorldForm_SettingsGrid_ColumnCreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LoadWorldForm_SettingsGrid_ColumnName {
            get {
                return ResourceManager.GetString("LoadWorldForm_SettingsGrid_ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new world has been created!
        ///
        ///Right click a village if you don&apos;t know where to start..
        /// </summary>
        internal static string NewWorldForm_Created {
            get {
                return ResourceManager.GetString("NewWorldForm_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can later still specify yourself through the World -&gt; &apos;Select Active Player&apos; menu..
        /// </summary>
        internal static string NewWorldForm_Created_NoYou1 {
            get {
                return ResourceManager.GetString("NewWorldForm_Created_NoYou1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note that for example planning attacks will work much easier when you have selected yourself..
        /// </summary>
        internal static string NewWorldForm_Created_NoYou2 {
            get {
                return ResourceManager.GetString("NewWorldForm_Created_NoYou2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Created!.
        /// </summary>
        internal static string NewWorldForm_CreatedTitle {
            get {
                return ResourceManager.GetString("NewWorldForm_CreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get a list of village coordinates somehow, paste them in the box on the left and they will appear in the grid on the right.
        ///
        ///Use Control + A to select all imported villages. Right click to set their purpose or to attack them.
        ///
        ///You can find more information at Windows &gt; &apos;Manage your villages&apos; :).
        /// </summary>
        internal static string VillageCoordinatesImporterForm_Help {
            get {
                return ResourceManager.GetString("VillageCoordinatesImporterForm_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import village coordinates?.
        /// </summary>
        internal static string VillageCoordinatesImporterForm_Help_Title {
            get {
                return ResourceManager.GetString("VillageCoordinatesImporterForm_Help_Title", resourceCulture);
            }
        }
    }
}
